use std::ffi::c_void;
use std::sync::OnceLock;

use faer::col::AsColRef;
use faer::linalg::solvers::{
    DenseSolveCore,
    Eigen,
    Llt,
    PartialPivLu,
    Qr,
    SelfAdjointEigen,
    Solve,
    SolveLstsq,
    Svd,
};
use faer::Side;

use crate::lean::*;
use crate::matrix;
use crate::scalar::FaerScalar;

/* Macro for external class registration boilerplate **************************/

macro_rules! decomp_class {
    (
        $ty:ty,
        $wrapper:ident,
        $lock:ident,
        $finalize:ident,
        $foreach:ident,
        $get_class:ident,
        $wrap:ident,
        $unwrap:ident
    ) => {
        struct $wrapper(*mut LeanExternalClass);
        unsafe impl Send for $wrapper {}
        unsafe impl Sync for $wrapper {}

        static $lock: OnceLock<$wrapper> = OnceLock::new();

        unsafe extern "C" fn $finalize(ptr: *mut c_void) {
            drop(Box::from_raw(ptr as *mut $ty));
        }

        unsafe extern "C" fn $foreach(
            _ptr: *mut c_void,
            _child: BLeanObjArg
        ) { }

        fn $get_class() -> *mut LeanExternalClass {
            $lock
                .get_or_init(|| unsafe {
                    $wrapper(
                        lean_register_external_class(
                            Some($finalize),
                            Some($foreach),
                        )
                    )
                }).0
        }

        unsafe fn $wrap(v: $ty) -> LeanObjRes {
            let boxed = Box::into_raw(Box::new(v));
            faermat_lean_alloc_external($get_class(), boxed as *mut c_void)
        }

        unsafe fn $unwrap(o: BLeanObjArg) -> &'static $ty {
            let ptr = faermat_lean_get_external_data(o);
            &*(ptr as *const $ty)
        }
    };
}

/* LU (partial pivoting) -- f64 ***********************************************/
// f64 (Lean's Float) is unboxed at the ABI level: scalars pass as
// raw C doubles, not as boxed Lean objects. Functions like det and
// eigenvalue accessors have different C signatures from the boxed-
// scalar versions generated by the decomp macros for f32/c64/c32.
// Because of this, f64 decomposition FFI functions are written out
// manually.

decomp_class!(
    PartialPivLu<f64>,
    LuClassPtr,
    LU_CLASS_F64,
    finalize_lu_f64,
    foreach_lu_f64,
    get_lu_class_f64,
    wrap_lu_f64,
    unwrap_lu_f64
);

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_lu_f64(m: BLeanObjArg) -> LeanObjRes {
    let r = matrix::unwrap_f64(m).as_ref();
    let lu = PartialPivLu::new(r);
    wrap_lu_f64(lu)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_lu_solve_f64(lu: BLeanObjArg, b: BLeanObjArg)
    -> LeanObjRes
{
    let decomp = unwrap_lu_f64(lu);
    let rhs = matrix::unwrap_f64(b).as_ref();
    let result = decomp.solve(rhs);
    matrix::wrap_f64(result)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_lu_solve_vec_f64(
    lu: BLeanObjArg,
    b: BLeanObjArg,
) -> LeanObjRes
{
    let decomp = unwrap_lu_f64(lu);
    let col = crate::vector::unwrap_f64(b).as_col_ref();
    let mut rhs_mat: faer::Mat<f64> = faer::Mat::zeros(col.nrows(), 1);
    rhs_mat.col_mut(0).copy_from(col);
    let result = decomp.solve(rhs_mat.as_ref());
    let out = result.col(0).to_owned();
    crate::vector::wrap_f64(out)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_lu_det_f64(m: BLeanObjArg) -> f64 {
    let r = matrix::unwrap_f64(m).as_ref();
    r.determinant()
}

#[no_mangle]
pub unsafe extern "C" fn faermat_lu_inverse_f64(lu: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_lu_f64(lu);
    matrix::wrap_f64(decomp.inverse())
}

#[no_mangle]
pub unsafe extern "C" fn faermat_lu_L_f64(lu: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_lu_f64(lu);
    matrix::wrap_f64(decomp.L().to_owned())
}

#[no_mangle]
pub unsafe extern "C" fn faermat_lu_U_f64(lu: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_lu_f64(lu);
    matrix::wrap_f64(decomp.U().to_owned())
}

/* QR *************************************************************************/

decomp_class!(
    Qr<f64>,
    QrClassPtr,
    QR_CLASS_F64,
    finalize_qr_f64,
    foreach_qr_f64,
    get_qr_class_f64,
    wrap_qr_f64,
    unwrap_qr_f64
);

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_qr_f64(m: BLeanObjArg) -> LeanObjRes {
    let r = matrix::unwrap_f64(m).as_ref();
    let qr = Qr::new(r);
    wrap_qr_f64(qr)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_qr_Q_f64(qr: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_qr_f64(qr);
    matrix::wrap_f64(decomp.compute_thin_Q())
}

#[no_mangle]
pub unsafe extern "C" fn faermat_qr_R_f64(qr: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_qr_f64(qr);
    matrix::wrap_f64(decomp.thin_R().to_owned())
}

#[no_mangle]
pub unsafe extern "C" fn faermat_qr_solve_f64(qr: BLeanObjArg,b: BLeanObjArg)
    -> LeanObjRes
{
    let decomp = unwrap_qr_f64(qr);
    let rhs = matrix::unwrap_f64(b).as_ref();
    let result = decomp.solve(rhs);
    matrix::wrap_f64(result)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_qr_solve_lstsq_f64(
    qr: BLeanObjArg,
    b: BLeanObjArg,
) -> LeanObjRes {
    let decomp = unwrap_qr_f64(qr);
    let rhs = matrix::unwrap_f64(b).as_ref();
    let result = decomp.solve_lstsq(rhs);
    matrix::wrap_f64(result)
}

/* Cholesky (LLT) *************************************************************/

decomp_class!(
    Llt<f64>,
    CholClassPtr,
    CHOL_CLASS_F64,
    finalize_chol_f64,
    foreach_chol_f64,
    get_chol_class_f64,
    wrap_chol_f64,
    unwrap_chol_f64
);

/// Returns Option: none if not positive definite.
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_cholesky_f64(m: BLeanObjArg)
    -> LeanObjRes
{
    let r = matrix::unwrap_f64(m).as_ref();
    match Llt::new(r, Side::Lower) {
        Ok(llt) => mk_option_some(wrap_chol_f64(llt)),
        Err(_) => mk_option_none(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn faermat_cholesky_L_f64(chol: BLeanObjArg)
    -> LeanObjRes
{
    let decomp = unwrap_chol_f64(chol);
    matrix::wrap_f64(decomp.L().to_owned())
}

#[no_mangle]
pub unsafe extern "C" fn faermat_cholesky_solve_f64(
    chol: BLeanObjArg,
    b: BLeanObjArg,
) -> LeanObjRes
{
    let decomp = unwrap_chol_f64(chol);
    let rhs = matrix::unwrap_f64(b).as_ref();
    let result = decomp.solve(rhs);
    matrix::wrap_f64(result)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_cholesky_inverse_f64(chol: BLeanObjArg)
    -> LeanObjRes
{
    let decomp = unwrap_chol_f64(chol);
    matrix::wrap_f64(decomp.inverse())
}

/* SVD (thin) *****************************************************************/

decomp_class!(
    Svd<f64>,
    SvdClassPtr,
    SVD_CLASS_F64,
    finalize_svd_f64,
    foreach_svd_f64,
    get_svd_class_f64,
    wrap_svd_f64,
    unwrap_svd_f64
);

/// Returns Option: none on convergence failure.
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_svd_f64(m: BLeanObjArg) -> LeanObjRes {
    let r = matrix::unwrap_f64(m).as_ref();
    match Svd::new_thin(r) {
        Ok(svd) => mk_option_some(wrap_svd_f64(svd)),
        Err(_) => mk_option_none(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn faermat_svd_U_f64(svd: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_svd_f64(svd);
    matrix::wrap_f64(decomp.U().to_owned())
}

#[no_mangle]
pub unsafe extern "C" fn faermat_svd_V_f64(svd: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_svd_f64(svd);
    matrix::wrap_f64(decomp.V().to_owned())
}

/// Returns singular values as Array Float.
#[no_mangle]
pub unsafe extern "C" fn faermat_svd_S_f64(svd: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_svd_f64(svd);
    let diag = decomp.S().column_vector();
    let n = diag.nrows();
    let mut vals = Vec::with_capacity(n);
    for i in 0..n {
        vals.push(diag[i]);
    }
    vec_to_array_float(&vals)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_svd_pseudoinverse_f64(svd: BLeanObjArg)
    -> LeanObjRes
{
    let decomp = unwrap_svd_f64(svd);
    matrix::wrap_f64(decomp.pseudoinverse())
}

#[no_mangle]
pub unsafe extern "C" fn faermat_svd_solve_lstsq_f64(
    svd: BLeanObjArg,
    b: BLeanObjArg,
) -> LeanObjRes
{
    let decomp = unwrap_svd_f64(svd);
    let rhs = matrix::unwrap_f64(b).as_ref();
    let result = decomp.solve_lstsq(rhs);
    matrix::wrap_f64(result)
}

/* Self-adjoint eigendecomposition ********************************************/

decomp_class!(
    SelfAdjointEigen<f64>,
    EigenClassPtr,
    EIGEN_CLASS_F64,
    finalize_eigen_f64,
    foreach_eigen_f64,
    get_eigen_class_f64,
    wrap_eigen_f64,
    unwrap_eigen_f64
);

/// Returns Option: none on convergence failure.
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_selfadjoint_eigen_f64(m: BLeanObjArg)
    -> LeanObjRes
{
    let r = matrix::unwrap_f64(m).as_ref();
    match SelfAdjointEigen::new(r, Side::Lower) {
        Ok(evd) => mk_option_some(wrap_eigen_f64(evd)),
        Err(_) => mk_option_none(),
    }
}

/// Returns eigenvectors as a Matrix.
#[no_mangle]
pub unsafe extern "C" fn faermat_selfadjoint_eigen_U_f64(evd: BLeanObjArg)
    -> LeanObjRes
{
    let decomp = unwrap_eigen_f64(evd);
    matrix::wrap_f64(decomp.U().to_owned())
}

/// Returns eigenvalues as Array Float.
#[no_mangle]
pub unsafe extern "C" fn faermat_selfadjoint_eigen_S_f64(evd: BLeanObjArg)
    -> LeanObjRes
{
    let decomp = unwrap_eigen_f64(evd);
    let diag = decomp.S().column_vector();
    let n = diag.nrows();
    let mut vals = Vec::with_capacity(n);
    for i in 0..n {
        vals.push(diag[i]);
    }
    vec_to_array_float(&vals)
}

decomp_class!(
    Eigen<f32>,
    EigenGenPtrF32,
    EIGEN_GEN_CLASS_F32,
    finalize_eigen_gen_f32,
    foreach_eigen_gen_f32,
    get_eigen_gen_class_f32,
    wrap_eigen_gen_f32,
    unwrap_eigen_gen_f32
);

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_eigen_f32(m: BLeanObjArg) -> LeanObjRes {
    let r = matrix::unwrap_f32(m).as_ref();
    match Eigen::new_from_real(r) {
        Ok(evd) => mk_option_some(wrap_eigen_gen_f32(evd)),
        Err(_) => mk_option_none(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn faermat_eigen_U_f32(evd: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_eigen_gen_f32(evd);
    matrix::wrap_c32(decomp.U().to_owned())
}

#[no_mangle]
pub unsafe extern "C" fn faermat_eigen_S_f32(evd: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_eigen_gen_f32(evd);
    let diag = decomp.S().column_vector();
    let n = diag.nrows();
    let mut vals = Vec::with_capacity(n);
    for i in 0..n { vals.push(diag[i]); }
    vec_to_array_complex_f32(&vals)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_eigenvalues_f32(m: BLeanObjArg)
    -> LeanObjRes
{
    let r = matrix::unwrap_f32(m).as_ref();
    match r.eigenvalues() {
        Ok(vals) => mk_option_some(vec_to_array_complex_f32(&vals)),
        Err(_) => mk_option_none(),
    }
}
/* Convenience functions on Matrix ********************************************/

/// Singular values only (no U, V).
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_singular_values_f64(m: BLeanObjArg)
    -> LeanObjRes
{
    let r = matrix::unwrap_f64(m).as_ref();
    match r.singular_values() {
        Ok(vals) => mk_option_some(vec_to_array_float(&vals)),
        Err(_) => mk_option_none(),
    }
}

/// Self-adjoint eigenvalues only.
#[no_mangle]
pub unsafe extern "C"
fn faermat_mat_selfadjoint_eigenvalues_f64(m: BLeanObjArg) -> LeanObjRes {
    let r = matrix::unwrap_f64(m).as_ref();
    match r.self_adjoint_eigenvalues(Side::Lower) {
        Ok(vals) => mk_option_some(vec_to_array_float(&vals)),
        Err(_) => mk_option_none(),
    }
}

/* General eigendecomposition (real matrices -> complex results) **************/

decomp_class!(
    Eigen<f64>,
    EigenGenPtr,
    EIGEN_GEN_CLASS_F64,
    finalize_eigen_gen_f64,
    foreach_eigen_gen_f64,
    get_eigen_gen_class_f64,
    wrap_eigen_gen_f64,
    unwrap_eigen_gen_f64
);

/// Compute general eigendecomposition of a real
/// matrix. Returns Option: none on convergence
/// failure.
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_eigen_f64(m: BLeanObjArg) -> LeanObjRes {
    let r = matrix::unwrap_f64(m).as_ref();
    match Eigen::new_from_real(r) {
        Ok(evd) => mk_option_some(wrap_eigen_gen_f64(evd)),
        Err(_) => mk_option_none(),
    }
}

/// Returns eigenvectors as Matrix C64.
#[no_mangle]
pub unsafe extern "C" fn faermat_eigen_U_f64(evd: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_eigen_gen_f64(evd);
    matrix::wrap_c64(decomp.U().to_owned())
}

/// Returns eigenvalues as Array C64.
#[no_mangle]
pub unsafe extern "C" fn faermat_eigen_S_f64(evd: BLeanObjArg) -> LeanObjRes {
    let decomp = unwrap_eigen_gen_f64(evd);
    let diag = decomp.S().column_vector();
    let n = diag.nrows();
    let mut vals = Vec::with_capacity(n);
    for i in 0..n { vals.push(diag[i]); }
    vec_to_array_complex_f64(&vals)
}

/// Eigenvalues only (no eigenvectors).
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_eigenvalues_f64(m: BLeanObjArg)
    -> LeanObjRes
{
    let r = matrix::unwrap_f64(m).as_ref();
    match r.eigenvalues() {
        Ok(vals) => mk_option_some(vec_to_array_complex_f64(&vals)),
        Err(_) => mk_option_none(),
    }
}

/* DecompScalar: wrap/unwrap dispatch for macros ******************************/

trait DecompScalar: FaerScalar {
    unsafe fn wrap_mat(m: faer::Mat<Self>) -> LeanObjRes;
    unsafe fn unwrap_mat(o: BLeanObjArg) -> &'static matrix::MatrixInner<Self>;
    unsafe fn wrap_vec(v: faer::Col<Self>) -> LeanObjRes;
    unsafe fn unwrap_vec(o: BLeanObjArg) -> &'static faer::Col<Self>;
}

impl DecompScalar for f64 {
    unsafe fn wrap_mat(m: faer::Mat<Self>) -> LeanObjRes {
        matrix::wrap_f64(m)
    }
    unsafe fn unwrap_mat(o: BLeanObjArg) -> &'static matrix::MatrixInner<Self> {
        matrix::unwrap_f64(o)
    }
    unsafe fn wrap_vec(v: faer::Col<Self>) -> LeanObjRes {
        crate::vector::wrap_f64(v)
    }
    unsafe fn unwrap_vec(o: BLeanObjArg) -> &'static faer::Col<Self> {
        crate::vector::unwrap_f64(o)
    }
}

impl DecompScalar for f32 {
    unsafe fn wrap_mat(m: faer::Mat<Self>) -> LeanObjRes {
        matrix::wrap_f32(m)
    }
    unsafe fn unwrap_mat(o: BLeanObjArg) -> &'static matrix::MatrixInner<Self> {
        matrix::unwrap_f32(o)
    }
    unsafe fn wrap_vec(v: faer::Col<Self>) -> LeanObjRes {
        crate::vector::wrap_f32(v)
    }
    unsafe fn unwrap_vec(o: BLeanObjArg) -> &'static faer::Col<Self> {
        crate::vector::unwrap_f32(o)
    }
}

impl DecompScalar for num_complex::Complex<f64> {
    unsafe fn wrap_mat(m: faer::Mat<Self>) -> LeanObjRes {
        matrix::wrap_c64(m)
    }
    unsafe fn unwrap_mat(o: BLeanObjArg) -> &'static matrix::MatrixInner<Self> {
        matrix::unwrap_c64(o)
    }
    unsafe fn wrap_vec(v: faer::Col<Self>) -> LeanObjRes {
        crate::vector::wrap_c64(v)
    }
    unsafe fn unwrap_vec(o: BLeanObjArg) -> &'static faer::Col<Self> {
        crate::vector::unwrap_c64(o)
    }
}

impl DecompScalar for num_complex::Complex<f32> {
    unsafe fn wrap_mat(m: faer::Mat<Self>) -> LeanObjRes {
        matrix::wrap_c32(m)
    }
    unsafe fn unwrap_mat(o: BLeanObjArg) -> &'static matrix::MatrixInner<Self> {
        matrix::unwrap_c32(o)
    }
    unsafe fn wrap_vec(v: faer::Col<Self>) -> LeanObjRes {
        crate::vector::wrap_c32(v)
    }
    unsafe fn unwrap_vec(o: BLeanObjArg) -> &'static faer::Col<Self> {
        crate::vector::unwrap_c32(o)
    }
}

/* LU *************************************************************************/

macro_rules! lu_ffi {
    ($suffix:ident, $scalar:ty) => { paste::paste!(
        decomp_class!(
            PartialPivLu<$scalar>,
            [<LuPtr $suffix:upper>],
            [<LU_CLS_ $suffix:upper>],
            [<fin_lu_ $suffix>], [<fe_lu_ $suffix>],
            [<cls_lu_ $suffix>],
            [<wrap_lu_ $suffix>],
            [<unwrap_lu_ $suffix>]
        );

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_mat_lu_ $suffix>](m: BLeanObjArg)
            -> LeanObjRes
        {
            let r = <$scalar as DecompScalar>::unwrap_mat(m).as_ref();
            [<wrap_lu_ $suffix>](PartialPivLu::new(r))
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_lu_solve_ $suffix>](
            lu: BLeanObjArg,
            b: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_lu_ $suffix>](lu);
            let rhs = <$scalar as DecompScalar>::unwrap_mat(b).as_ref();
            <$scalar as DecompScalar>::wrap_mat(d.solve(rhs))
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_lu_solve_vec_ $suffix>](
            lu: BLeanObjArg,
            b: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_lu_ $suffix>](lu);
            let col = <$scalar as DecompScalar>::unwrap_vec(b).as_col_ref();
            let mut rhs: faer::Mat<$scalar> = faer::Mat::zeros(col.nrows(), 1);
            rhs.col_mut(0).copy_from(col);
            let res = d.solve(rhs.as_ref());
            let out = res.col(0).to_owned();
            <$scalar as DecompScalar>::wrap_vec(out)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_lu_det_ $suffix>](m: BLeanObjArg)
            -> LeanObjRes
        {
            let r = <$scalar as DecompScalar>::unwrap_mat(m).as_ref();
            <$scalar as FaerScalar>::box_scalar(r.determinant())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_lu_inverse_ $suffix>](
            lu: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_lu_ $suffix>](lu);
            <$scalar as DecompScalar>::wrap_mat(d.inverse())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_lu_L_ $suffix>](lu: BLeanObjArg)
            -> LeanObjRes
        {
            let d = [<unwrap_lu_ $suffix>](lu);
            <$scalar as DecompScalar>::wrap_mat(d.L().to_owned())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_lu_U_ $suffix>](lu: BLeanObjArg)
            -> LeanObjRes
        {
            let d = [<unwrap_lu_ $suffix>](lu);
            <$scalar as DecompScalar>::wrap_mat(d.U().to_owned())
        }
    ); }
}

/* QR *************************************************************************/

macro_rules! qr_ffi {
    ($suffix:ident, $scalar:ty) => { paste::paste!(
        decomp_class!(
            Qr<$scalar>,
            [<QrPtr $suffix:upper>],
            [<QR_CLS_ $suffix:upper>],
            [<fin_qr_ $suffix>], [<fe_qr_ $suffix>],
            [<cls_qr_ $suffix>],
            [<wrap_qr_ $suffix>],
            [<unwrap_qr_ $suffix>]
        );

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_mat_qr_ $suffix>](m: BLeanObjArg)
            -> LeanObjRes
        {
            let r = <$scalar as DecompScalar>::unwrap_mat(m).as_ref();
            [<wrap_qr_ $suffix>](Qr::new(r))
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_qr_Q_ $suffix>](qr: BLeanObjArg)
            -> LeanObjRes
        {
            let d = [<unwrap_qr_ $suffix>](qr);
            <$scalar as DecompScalar>::wrap_mat(d.compute_thin_Q())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_qr_R_ $suffix>](qr: BLeanObjArg)
            -> LeanObjRes
        {
            let d = [<unwrap_qr_ $suffix>](qr);
            <$scalar as DecompScalar>::wrap_mat(d.thin_R().to_owned())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_qr_solve_ $suffix>](
            qr: BLeanObjArg,
            b: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_qr_ $suffix>](qr);
            let rhs = <$scalar as DecompScalar>::unwrap_mat(b).as_ref();
            <$scalar as DecompScalar>::wrap_mat(d.solve(rhs))
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_qr_solve_lstsq_ $suffix>](
            qr: BLeanObjArg,
            b: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_qr_ $suffix>](qr);
            let rhs = <$scalar as DecompScalar>::unwrap_mat(b).as_ref();
            <$scalar as DecompScalar>::wrap_mat(d.solve_lstsq(rhs))
        }
    ); }
}

/* Cholesky *******************************************************************/

macro_rules! cholesky_ffi {
    ($suffix:ident, $scalar:ty) => { paste::paste!(
        decomp_class!(
            Llt<$scalar>,
            [<CholPtr $suffix:upper>],
            [<CHOL_CLS_ $suffix:upper>],
            [<fin_chol_ $suffix>],
            [<fe_chol_ $suffix>],
            [<cls_chol_ $suffix>],
            [<wrap_chol_ $suffix>],
            [<unwrap_chol_ $suffix>]
        );

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_mat_cholesky_ $suffix>](
            m: BLeanObjArg,
        ) -> LeanObjRes
        {
            let r = <$scalar as DecompScalar>::unwrap_mat(m).as_ref();
            match Llt::new(r, Side::Lower) {
                Ok(llt) => mk_option_some([<wrap_chol_ $suffix>](llt)),
                Err(_) => mk_option_none(),
            }
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_cholesky_L_ $suffix>](
            chol: BLeanObjArg
        ) -> LeanObjRes
        {
            let d = [<unwrap_chol_ $suffix>](chol);
            <$scalar as DecompScalar>::wrap_mat(d.L().to_owned())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_cholesky_solve_ $suffix>](
            chol: BLeanObjArg,
            b: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_chol_ $suffix>](chol);
            let rhs = <$scalar as DecompScalar>::unwrap_mat(b).as_ref();
            <$scalar as DecompScalar>::wrap_mat(d.solve(rhs))
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_cholesky_inverse_ $suffix>](
            chol: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_chol_ $suffix>](chol);
            <$scalar as DecompScalar>::wrap_mat(d.inverse())
        }
    ); }
}

/* SVD ************************************************************************/

macro_rules! svd_ffi {
    ($suffix:ident, $scalar:ty, $real:ty) => { paste::paste!(
        decomp_class!(
            Svd<$scalar>,
            [<SvdPtr $suffix:upper>],
            [<SVD_CLS_ $suffix:upper>],
            [<fin_svd_ $suffix>],
            [<fe_svd_ $suffix>],
            [<cls_svd_ $suffix>],
            [<wrap_svd_ $suffix>],
            [<unwrap_svd_ $suffix>]
        );

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_mat_svd_ $suffix>](m: BLeanObjArg)
            -> LeanObjRes
        {
            let r = <$scalar as DecompScalar>::unwrap_mat(m).as_ref();
            match Svd::new_thin(r) {
                Ok(svd) => mk_option_some([<wrap_svd_ $suffix>](svd)),
                Err(_) => mk_option_none(),
            }
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_svd_U_ $suffix>](svd: BLeanObjArg)
            -> LeanObjRes
        {
            let d = [<unwrap_svd_ $suffix>](svd);
            <$scalar as DecompScalar>::wrap_mat(d.U().to_owned())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_svd_V_ $suffix>](svd: BLeanObjArg)
            -> LeanObjRes
        {
            let d = [<unwrap_svd_ $suffix>](svd);
            <$scalar as DecompScalar>::wrap_mat(d.V().to_owned())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_svd_S_ $suffix>](svd: BLeanObjArg)
            -> LeanObjRes
        {
            let d = [<unwrap_svd_ $suffix>](svd);
            let diag = d.S().column_vector();
            let n = diag.nrows();
            let mut vals: Vec<$real> = Vec::with_capacity(n);
            for i in 0..n {
                vals.push(
                    <$scalar as faer_traits::ComplexField>::real_part_impl(
                        &diag[i]
                    ),
                );
            }
            <$real as FaerScalar>::vec_to_array(&vals)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_svd_pseudoinverse_ $suffix>](
            svd: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_svd_ $suffix>](svd);
            <$scalar as DecompScalar>::wrap_mat(d.pseudoinverse())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_svd_solve_lstsq_ $suffix>](
            svd: BLeanObjArg,
            b: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_svd_ $suffix>](svd);
            let rhs = <$scalar as DecompScalar>::unwrap_mat(b).as_ref();
            <$scalar as DecompScalar>::wrap_mat(d.solve_lstsq(rhs))
        }
    ); }
}

/* SelfAdjointEigen ***********************************************************/

macro_rules! selfadjoint_eigen_ffi {
    ($suffix:ident, $scalar:ty, $real:ty) => { paste::paste!(
        decomp_class!(
            SelfAdjointEigen<$scalar>,
            [<SaePtr $suffix:upper>],
            [<SAE_CLS_ $suffix:upper>],
            [<fin_sae_ $suffix>],
            [<fe_sae_ $suffix>],
            [<cls_sae_ $suffix>],
            [<wrap_sae_ $suffix>],
            [<unwrap_sae_ $suffix>]
        );

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_mat_selfadjoint_eigen_ $suffix>](
            m: BLeanObjArg,
        ) -> LeanObjRes
        {
            let r = <$scalar as DecompScalar>::unwrap_mat(m).as_ref();
            match SelfAdjointEigen::new(r, Side::Lower) {
                Ok(evd) => mk_option_some([<wrap_sae_ $suffix>](evd)),
                Err(_) => mk_option_none(),
            }
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_selfadjoint_eigen_U_ $suffix>](
            evd: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_sae_ $suffix>](evd);
            <$scalar as DecompScalar>::wrap_mat(d.U().to_owned())
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_selfadjoint_eigen_S_ $suffix>](
            evd: BLeanObjArg,
        ) -> LeanObjRes
        {
            let d = [<unwrap_sae_ $suffix>](evd);
            let diag = d.S().column_vector();
            let n = diag.nrows();
            let mut vals: Vec<$real> = Vec::with_capacity(n);
            for i in 0..n {
                vals.push(
                    <$scalar as faer_traits::ComplexField>::real_part_impl(
                        &diag[i]
                    ),
                );
            }
            <$real as FaerScalar>::vec_to_array(&vals)
        }
    ); }
}

/* convenience functions ******************************************************/

macro_rules! convenience_ffi {
    ($suffix:ident, $scalar:ty, $real:ty) => { paste::paste!(
        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_mat_singular_values_ $suffix>](
            m: BLeanObjArg,
        ) -> LeanObjRes
        {
            let r = <$scalar as DecompScalar>::unwrap_mat(m).as_ref();
            match r.singular_values() {
                Ok(vals) => mk_option_some(
                    <$real as FaerScalar>::vec_to_array(&vals)
                ),
                Err(_) => mk_option_none(),
            }
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_mat_selfadjoint_eigenvalues_ $suffix>](
            m: BLeanObjArg,
        ) -> LeanObjRes {
            let r = <$scalar as DecompScalar>::unwrap_mat(m).as_ref();
            match r.self_adjoint_eigenvalues(Side::Lower) {
                Ok(vals) => mk_option_some(
                    <$real as FaerScalar>::vec_to_array(&vals)
                ),
                Err(_) => mk_option_none(),
            }
        }
    ); }
}

/* Matrix functions via Eigen *************************************************/

use num_complex::Complex;

/// Compute f(A) = V * diag(f(lambda)) * V^* for a real input matrix.
/// Returns a complex result matrix.
unsafe fn matfn_eigen_real_f64<F>(m: BLeanObjArg, f: F)
    -> Option<faer::Mat<Complex<f64>>>
where F: Fn(Complex<f64>) -> Complex<f64>
{
    let r = matrix::unwrap_f64(m).as_ref();
    if r.nrows() != r.ncols() { return None; }
    let evd = Eigen::<f64>::new_from_real(r).ok()?;
    let n = r.nrows();
    let v = evd.U();
    let s = evd.S();
    // Build V * diag(f(lambda))
    let mut vd: faer::Mat<Complex<f64>> = faer::Mat::zeros(n, n);
    for j in 0 .. n {
        let lam = s.column_vector()[j];
        let fl = f(lam);
        for i in 0 .. n {
            vd[(i, j)] = v[(i, j)] * fl;
        }
    }
    let v_adj = v.adjoint();
    Some(&vd * &v_adj)
}

unsafe fn matfn_eigen_real_f32<F>(m: BLeanObjArg, f: F)
    -> Option<faer::Mat<Complex<f32>>>
where F: Fn(Complex<f32>) -> Complex<f32>
{
    let r = matrix::unwrap_f32(m).as_ref();
    if r.nrows() != r.ncols() { return None; }
    let evd = Eigen::<f32>::new_from_real(r).ok()?;
    let n = r.nrows();
    let v = evd.U();
    let s = evd.S();
    let mut vd: faer::Mat<Complex<f32>> = faer::Mat::zeros(n, n);
    for j in 0 .. n {
        let lam = s.column_vector()[j];
        let fl = f(lam);
        for i in 0 .. n {
            vd[(i, j)] = v[(i, j)] * fl;
        }
    }
    let v_adj = v.adjoint();
    Some(&vd * &v_adj)
}

unsafe fn matfn_eigen_c64<F>(m: BLeanObjArg, f: F)
    -> Option<faer::Mat<Complex<f64>>>
where F: Fn(Complex<f64>) -> Complex<f64>
{
    let r = matrix::unwrap_c64(m).as_ref();
    if r.nrows() != r.ncols() { return None; }
    let evd = Eigen::<f64>::new(r).ok()?;
    let n = r.nrows();
    let v = evd.U();
    let s = evd.S();
    let mut vd: faer::Mat<Complex<f64>> = faer::Mat::zeros(n, n);
    for j in 0 .. n {
        let lam = s.column_vector()[j];
        let fl = f(lam);
        for i in 0 .. n {
            vd[(i, j)] = v[(i, j)] * fl;
        }
    }
    let v_adj = v.adjoint();
    Some(&vd * &v_adj)
}

unsafe fn matfn_eigen_c32<F>(m: BLeanObjArg, f: F)
    -> Option<faer::Mat<Complex<f32>>>
where F: Fn(Complex<f32>) -> Complex<f32>
{
    let r = matrix::unwrap_c32(m).as_ref();
    if r.nrows() != r.ncols() { return None; }
    let evd = Eigen::<f32>::new(r).ok()?;
    let n = r.nrows();
    let v = evd.U();
    let s = evd.S();
    let mut vd: faer::Mat<Complex<f32>> = faer::Mat::zeros(n, n);
    for j in 0 .. n {
        let lam = s.column_vector()[j];
        let fl = f(lam);
        for i in 0 .. n {
            vd[(i, j)] = v[(i, j)] * fl;
        }
    }
    let v_adj = v.adjoint();
    Some(&vd * &v_adj)
}

/// Extract real part of a complex matrix.
fn extract_real_f64(m: &faer::Mat<Complex<f64>>) -> faer::Mat<f64> {
    m.map(|elem| elem.re)
}

fn extract_real_f32(m: &faer::Mat<Complex<f32>>) -> faer::Mat<f32> {
    m.map(|elem| elem.re)
}

// expm: real input -> real output
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_expm_f64(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_real_f64(m, |z| z.exp()) {
        Some(c) => mk_option_some(matrix::wrap_f64(extract_real_f64(&c))),
        None => mk_option_none(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_expm_f32(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_real_f32(m, |z| z.exp()) {
        Some(c) => mk_option_some(matrix::wrap_f32(extract_real_f32(&c))),
        None => mk_option_none(),
    }
}

// expm: complex input -> complex output
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_expm_c64(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_c64(m, |z| z.exp()) {
        Some(c) => mk_option_some(matrix::wrap_c64(c)),
        None => mk_option_none(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_expm_c32(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_c32(m, |z| z.exp()) {
        Some(c) => mk_option_some(matrix::wrap_c32(c)),
        None => mk_option_none(),
    }
}

// sqrtm: real input -> complex output
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_sqrtm_f64(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_real_f64(m, |z| z.sqrt()) {
        Some(c) => mk_option_some(matrix::wrap_c64(c)),
        None => mk_option_none(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_sqrtm_f32(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_real_f32(m, |z| z.sqrt()) {
        Some(c) => mk_option_some(matrix::wrap_c32(c)),
        None => mk_option_none(),
    }
}

// sqrtm: complex input -> complex output
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_sqrtm_c64(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_c64(m, |z| z.sqrt()) {
        Some(c) => mk_option_some(matrix::wrap_c64(c)),
        None => mk_option_none(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_sqrtm_c32(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_c32(m, |z| z.sqrt()) {
        Some(c) => mk_option_some(matrix::wrap_c32(c)),
        None => mk_option_none(),
    }
}

// logm: real input -> complex output
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_logm_f64(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_real_f64(m, |z| z.ln()) {
        Some(c) => mk_option_some(matrix::wrap_c64(c)),
        None => mk_option_none(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_logm_f32(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_real_f32(m, |z| z.ln()) {
        Some(c) => mk_option_some(matrix::wrap_c32(c)),
        None => mk_option_none(),
    }
}

// logm: complex input -> complex output
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_logm_c64(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_c64(m, |z| z.ln()) {
        Some(c) => mk_option_some(matrix::wrap_c64(c)),
        None => mk_option_none(),
    }
}

#[no_mangle]
pub unsafe extern "C" fn faermat_mat_logm_c32(m: BLeanObjArg) -> LeanObjRes {
    match matfn_eigen_c32(m, |z| z.ln()) {
        Some(c) => mk_option_some(matrix::wrap_c32(c)),
        None => mk_option_none(),
    }
}

/* Instantiate for f32, c64, c32 **********************************************/

lu_ffi!(f32, f32);
lu_ffi!(c64, num_complex::Complex<f64>);
lu_ffi!(c32, num_complex::Complex<f32>);

qr_ffi!(f32, f32);
qr_ffi!(c64, num_complex::Complex<f64>);
qr_ffi!(c32, num_complex::Complex<f32>);

cholesky_ffi!(f32, f32);
cholesky_ffi!(c64, num_complex::Complex<f64>);
cholesky_ffi!(c32, num_complex::Complex<f32>);

svd_ffi!(f32, f32, f32);
svd_ffi!(c64, num_complex::Complex<f64>, f64);
svd_ffi!(c32, num_complex::Complex<f32>, f32);

selfadjoint_eigen_ffi!(f32, f32, f32);
selfadjoint_eigen_ffi!(c64, num_complex::Complex<f64>, f64);
selfadjoint_eigen_ffi!(c32, num_complex::Complex<f32>, f32);

convenience_ffi!(f32, f32, f32);
convenience_ffi!(c64, num_complex::Complex<f64>, f64);
convenience_ffi!(c32, num_complex::Complex<f32>, f32);

