use std::ffi::c_void;
use std::sync::{Arc, OnceLock};

use faer::col::AsColRef;
use faer::Col;

use crate::lean::*;
use crate::matrix;
use crate::scalar::FaerScalar;

/* Sync wrapper for external class pointer ************************************/

struct ClassPtr(*mut LeanExternalClass);
unsafe impl Send for ClassPtr { }
unsafe impl Sync for ClassPtr { }

/* External class *************************************************************/

static VEC_CLASS_F64: OnceLock<ClassPtr> = OnceLock::new();

unsafe extern "C" fn finalize_f64(ptr: *mut c_void) {
    drop(Box::from_raw(ptr as *mut Arc<Col<f64>>));
}

unsafe extern "C" fn foreach_f64(_ptr: *mut c_void, _child: BLeanObjArg) {
    // No Lean-object children to traverse.
}

fn get_class_f64() -> *mut LeanExternalClass {
    VEC_CLASS_F64
        .get_or_init(|| unsafe {
            ClassPtr(
                lean_register_external_class(
                    Some(finalize_f64),
                    Some(foreach_f64),
                )
            )
        }).0
}

pub unsafe fn wrap_f64(v: Col<f64>) -> LeanObjRes {
    let boxed = Box::into_raw(Box::new(Arc::new(v)));
    faermat_lean_alloc_external(
        get_class_f64(),
        boxed as *mut c_void,
    )
}

pub unsafe fn unwrap_f64(o: BLeanObjArg) -> &'static Col<f64> {
    let ptr = faermat_lean_get_external_data(o);
    &*(ptr as *const Arc<Col<f64>>)
}

/* f64 FFI ********************************************************************/
// f64 (Lean's Float) is unboxed at the ABI level: scalars pass as
// raw C doubles, not as boxed Lean objects. Functions like get, full,
// scale, set, and dot have different C signatures from the boxed-
// scalar versions generated by vector_ffi_boxed! for f32/c64/c32.
// Because of this, f64 FFI functions are written out manually.

/// Create a vector from a flat Array Float. Returns Option (Vector Float):
/// none if data is empty.
#[no_mangle]
pub unsafe extern "C" fn faermat_vec_of_array_f64(data: BLeanObjArg)
    -> LeanObjRes
{
    let vals = array_float_to_vec(data);
    let mut col: Col<f64> = Col::zeros(vals.len());
    col.iter_mut().zip(vals).for_each(|(elem, v)| { *elem = v; });
    mk_option_some(wrap_f64(col))
}

/// Create a zero vector.
#[no_mangle]
pub unsafe extern "C" fn faermat_vec_zeros_f64(n: u64) -> LeanObjRes {
    wrap_f64(Col::zeros(n as usize))
}

/// Create a vector filled with a constant.
#[no_mangle]
pub unsafe extern "C" fn faermat_vec_full_f64(n: u64, val: f64) -> LeanObjRes {
    let col = Col::full(n as usize, val);
    wrap_f64(col)
}

/* Inspection FFI *************************************************************/

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_len_f64(v: BLeanObjArg) -> u64 {
    unwrap_f64(v).nrows() as u64
}

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_get_f64(v: BLeanObjArg, i: u64) -> f64 {
    let col = unwrap_f64(v);
    col[i as usize]
}

/// Extract to a flat Array Float.
#[no_mangle]
pub unsafe extern "C" fn faermat_vec_to_array_f64(v: BLeanObjArg)
    -> LeanObjRes
{
    let col = unwrap_f64(v);
    let n = col.nrows();
    let mut vals = Vec::with_capacity(n);
    for i in 0..n { vals.push(col[i]); }
    vec_to_array_float(&vals)
}

/* Arithmetic FFI *************************************************************/

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_add_f64(a: BLeanObjArg, b: BLeanObjArg)
    -> LeanObjRes
{
    let va = unwrap_f64(a);
    let vb = unwrap_f64(b);
    if va.nrows() != vb.nrows() {
        let msg = c"Vector.add: length mismatch";
        lean_internal_panic(msg.as_ptr());
    }
    let result = va + vb;
    wrap_f64(result)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_sub_f64(a: BLeanObjArg, b: BLeanObjArg)
    -> LeanObjRes
{
    let va = unwrap_f64(a);
    let vb = unwrap_f64(b);
    if va.nrows() != vb.nrows() {
        let msg = c"Vector.sub: length mismatch";
        lean_internal_panic(msg.as_ptr());
    }
    let result = va - vb;
    wrap_f64(result)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_neg_f64(v: BLeanObjArg) -> LeanObjRes {
    let col = unwrap_f64(v);
    let result = -col;
    wrap_f64(result)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_scale_f64(s: f64, v: BLeanObjArg)
    -> LeanObjRes
{
    let col = unwrap_f64(v);
    let result = faer::Scale(s) * col;
    wrap_f64(result)
}

/// Dot product (inner product) of two vectors.
#[no_mangle]
pub unsafe extern "C" fn faermat_vec_dot_f64(a: BLeanObjArg, b: BLeanObjArg)
    -> f64
{
    let va = unwrap_f64(a).as_col_ref();
    let vb = unwrap_f64(b).as_col_ref();
    if va.nrows() != vb.nrows() {
        let msg = c"Vector.dot: length mismatch";
        lean_internal_panic(msg.as_ptr());
    }
    va.transpose() * vb
}

/// L2 norm.
#[no_mangle]
pub unsafe extern "C" fn faermat_vec_norm_f64(v: BLeanObjArg) -> f64 {
    unwrap_f64(v).as_col_ref().norm_l2()
}

/* Mat-vec mul ****************************************************************/

/// Matrix-vector product: M * v -> vector. Panics if dimensions mismatch.
#[no_mangle]
pub unsafe extern "C" fn faermat_mat_vec_mul_f64(m: BLeanObjArg, v: BLeanObjArg)
    -> LeanObjRes
{
    let mat = matrix::unwrap_f64(m).as_ref();
    let col = unwrap_f64(v).as_col_ref();
    if mat.ncols() != col.nrows() {
        let msg = c"Matrix * Vector: dimension mismatch";
        lean_internal_panic(msg.as_ptr());
    }
    let result = mat * col;
    wrap_f64(result)
}

/* Element set ****************************************************************/

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_set_f64(
    v: LeanObjArg, i: u64, val: f64,
) -> LeanObjRes
{
    let ii = i as usize;
    if faermat_lean_is_exclusive(v) {
        let ptr = faermat_lean_get_external_data(v);
        let arc = &mut *(ptr as *mut Arc<Col<f64>>);
        if Arc::strong_count(arc) == 1 {
            Arc::get_mut(arc).unwrap()[ii] = val;
        } else {
            let mut col = (**arc).clone();
            col[ii] = val;
            *arc = Arc::new(col);
        }
        v
    } else {
        let col_ref = unwrap_f64(v);
        let mut col = col_ref.clone();
        col[ii] = val;
        faermat_lean_dec(v);
        wrap_f64(col)
    }
}

/* f32/c64/c32 ****************************************************************/

macro_rules! vector_class {
    (
        $T:ty,
        $suffix:ident,
        $Wrapper:ident,
        $LOCK:ident,
        $finalize:ident,
        $foreach:ident,
        $get_class:ident
    ) => {
        struct $Wrapper(*mut LeanExternalClass);
        unsafe impl Send for $Wrapper { }
        unsafe impl Sync for $Wrapper { }
        static $LOCK: OnceLock<$Wrapper> = OnceLock::new();

        unsafe extern "C" fn $finalize(ptr: *mut c_void) {
            drop(Box::from_raw(ptr as *mut Arc<Col<$T>>));
        }
        unsafe extern "C" fn $foreach(
            _ptr: *mut c_void,
            _child: BLeanObjArg,
        ) { }

        fn $get_class() -> *mut LeanExternalClass {
            $LOCK
                .get_or_init(|| unsafe {
                    $Wrapper(
                        lean_register_external_class(
                            Some($finalize),
                            Some($foreach),
                        )
                    )
                }).0
        }

        paste::paste!(
            pub unsafe fn [<wrap_ $suffix>](v: Col<$T>) -> LeanObjRes {
                let boxed =
                    Box::into_raw(Box::new(Arc::new(v)));
                faermat_lean_alloc_external(
                    $get_class(),
                    boxed as *mut c_void,
                )
            }

            pub unsafe fn [<unwrap_ $suffix>](o: BLeanObjArg)
                -> &'static Col<$T>
            {
                let ptr = faermat_lean_get_external_data(o);
                &**(ptr as *const Arc<Col<$T>>)
            }
        );
    }
}

macro_rules! vector_ffi_boxed {
    ($T:ty, $suffix:ident, $mat_suffix:ident) => { paste::paste!(
        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_of_array_ $suffix>](
            data: BLeanObjArg,
        ) -> LeanObjRes
        {
            let vals = <$T as FaerScalar>::array_to_vec(data);
            let mut col: Col<$T> = Col::zeros(vals.len());
            col.iter_mut().zip(vals).for_each(|(elem, v)| { *elem = v; });
            mk_option_some([<wrap_ $suffix>](col))
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_zeros_ $suffix>](n: u64)
            -> LeanObjRes
        {
            [<wrap_ $suffix>](Col::<$T>::zeros(n as usize))
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_full_ $suffix>](
            n: u64,
            val: BLeanObjArg,
        ) -> LeanObjRes
        {
            let v = <$T as FaerScalar>::unbox_scalar(val);
            let col = Col::full(n as usize, v);
            [<wrap_ $suffix>](col)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_len_ $suffix>](v: BLeanObjArg)
            -> u64
        {
            [<unwrap_ $suffix>](v).nrows() as u64
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_get_ $suffix>](
            v: BLeanObjArg,
            i: u64,
        ) -> LeanObjRes
        {
            let col = [<unwrap_ $suffix>](v);
            <$T as FaerScalar>::box_scalar(col[i as usize])
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_to_array_ $suffix>](
            v: BLeanObjArg,
        ) -> LeanObjRes
        {
            let col = [<unwrap_ $suffix>](v);
            let n = col.nrows();
            let mut vals = Vec::with_capacity(n);
            for i in 0..n { vals.push(col[i]); }
            <$T as FaerScalar>::vec_to_array(&vals)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_add_ $suffix>](
            a: BLeanObjArg,
            b: BLeanObjArg,
        ) -> LeanObjRes
        {
            let va = [<unwrap_ $suffix>](a);
            let vb = [<unwrap_ $suffix>](b);
            if va.nrows() != vb.nrows() {
                let msg = c"Vector.add: length mismatch";
                lean_internal_panic(msg.as_ptr());
            }
            [<wrap_ $suffix>](va + vb)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_sub_ $suffix>](
            a: BLeanObjArg,
            b: BLeanObjArg,
        ) -> LeanObjRes
        {
            let va = [<unwrap_ $suffix>](a);
            let vb = [<unwrap_ $suffix>](b);
            if va.nrows() != vb.nrows() {
                let msg = c"Vector.sub: length mismatch";
                lean_internal_panic(msg.as_ptr());
            }
            [<wrap_ $suffix>](va - vb)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_neg_ $suffix>](v: BLeanObjArg)
            -> LeanObjRes
        {
            let col = [<unwrap_ $suffix>](v);
            [<wrap_ $suffix>](-col)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_scale_ $suffix>](
            s: BLeanObjArg,
            v: BLeanObjArg,
        ) -> LeanObjRes
        {
            let sv = <$T as FaerScalar>::unbox_scalar(s);
            let col = [<unwrap_ $suffix>](v);
            [<wrap_ $suffix>](faer::Scale(sv) * col)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_dot_ $suffix>](
            a: BLeanObjArg,
            b: BLeanObjArg,
        ) -> LeanObjRes
        {
            let va = [<unwrap_ $suffix>](a).as_col_ref();
            let vb = [<unwrap_ $suffix>](b).as_col_ref();
            if va.nrows() != vb.nrows() {
                let msg = c"Vector.dot: length mismatch";
                lean_internal_panic(msg.as_ptr());
            }
            <$T as FaerScalar>::box_scalar(va.transpose() * vb)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_mat_vec_mul_ $suffix>](
            m: BLeanObjArg,
            v: BLeanObjArg,
        ) -> LeanObjRes
        {
            let mat = matrix::[<unwrap_ $mat_suffix>](m).as_ref();
            let col = [<unwrap_ $suffix>](v).as_col_ref();
            if mat.ncols() != col.nrows() {
                let msg = c"Matrix * Vector: dimension mismatch";
                lean_internal_panic(msg.as_ptr());
            }
            [<wrap_ $suffix>](mat * col)
        }

        #[no_mangle]
        pub unsafe extern "C" fn [<faermat_vec_set_ $suffix>](
            v: LeanObjArg,
            i: u64,
            val: BLeanObjArg,
        ) -> LeanObjRes
        {
            let ii = i as usize;
            let scalar = <$T as FaerScalar>::unbox_scalar(val);
            if faermat_lean_is_exclusive(v) {
                let ptr = faermat_lean_get_external_data(v);
                let arc =
                    &mut *(ptr as *mut Arc<Col<$T>>);
                if Arc::strong_count(arc) == 1 {
                    Arc::get_mut(arc).unwrap()[ii] = scalar;
                } else {
                    let mut col = (**arc).clone();
                    col[ii] = scalar;
                    *arc = Arc::new(col);
                }
                v
            } else {
                let col_ref = [<unwrap_ $suffix>](v);
                let mut col = col_ref.clone();
                col[ii] = scalar;
                faermat_lean_dec(v);
                [<wrap_ $suffix>](col)
            }
        }

    ); }
}

vector_class!(
    f32,
    f32,
    VecF32Ptr,
    VEC_CLASS_F32,
    finalize_vec_f32,
    foreach_vec_f32,
    get_vec_class_f32
);
vector_ffi_boxed!(f32, f32, f32);

vector_class!(
    num_complex::Complex<f64>,
    c64,
    VecC64Ptr,
    VEC_CLASS_C64,
    finalize_vec_c64,
    foreach_vec_c64,
    get_vec_class_c64
);
vector_ffi_boxed!(num_complex::Complex<f64>, c64, c64);

vector_class!(
    num_complex::Complex<f32>,
    c32,
    VecC32Ptr,
    VEC_CLASS_C32,
    finalize_vec_c32,
    foreach_vec_c32,
    get_vec_class_c32
);
vector_ffi_boxed!(num_complex::Complex<f32>, c32, c32);

/* L2 norm Norm ***************************************************************/

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_norm_f32(v: BLeanObjArg) -> LeanObjRes {
    let n: f32 = unwrap_f32(v).as_col_ref().norm_l2();
    faermat_lean_box_float32(n)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_norm_c64(v: BLeanObjArg) -> f64 {
    unwrap_c64(v).as_col_ref().norm_l2()
}

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_norm_c32(v: BLeanObjArg) -> LeanObjRes {
    let n: f32 = unwrap_c32(v).as_col_ref().norm_l2();
    faermat_lean_box_float32(n)
}

/* Conjugate dot product ******************************************************/

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_conj_dot_f64(
    a: BLeanObjArg,
    b: BLeanObjArg,
) -> f64
{
    let va = unwrap_f64(a).as_col_ref();
    let vb = unwrap_f64(b).as_col_ref();
    if va.nrows() != vb.nrows() {
        let msg = c"Vector.conjDot: length mismatch";
        lean_internal_panic(msg.as_ptr());
    }
    va.transpose() * vb
}

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_conj_dot_f32(
    a: BLeanObjArg,
    b: BLeanObjArg,
) -> LeanObjRes
{
    let va = unwrap_f32(a).as_col_ref();
    let vb = unwrap_f32(b).as_col_ref();
    if va.nrows() != vb.nrows() {
        let msg = c"Vector.conjDot: length mismatch";
        lean_internal_panic(msg.as_ptr());
    }
    faermat_lean_box_float32(va.transpose() * vb)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_conj_dot_c64(
    a: BLeanObjArg,
    b: BLeanObjArg,
) -> LeanObjRes
{
    let va = unwrap_c64(a);
    let vb = unwrap_c64(b);
    let n = va.nrows();
    if n != vb.nrows() {
        let msg = c"Vector.conjDot: length mismatch";
        lean_internal_panic(msg.as_ptr());
    }
    let mut sum = num_complex::Complex::new(0.0, 0.0);
    for k in 0..n { sum += va[k].conj() * vb[k]; }
    box_complex_f64(sum)
}

#[no_mangle]
pub unsafe extern "C" fn faermat_vec_conj_dot_c32(
    a: BLeanObjArg,
    b: BLeanObjArg,
) -> LeanObjRes
{
    let va = unwrap_c32(a);
    let vb = unwrap_c32(b);
    let n = va.nrows();
    if n != vb.nrows() {
        let msg = c"Vector.conjDot: length mismatch";
        lean_internal_panic(msg.as_ptr());
    }
    let mut sum = num_complex::Complex::new(0.0f32, 0.0f32);
    for k in 0..n { sum += va[k].conj() * vb[k]; }
    box_complex_f32(sum)
}
